debugging actions

diff --git a/.github/workflows/validate_fasta.yml b/.github/workflows/validate_fasta.yml
--- a/.github/workflows/validate_fasta.yml
+++ b/.github/workflows/validate_fasta.yml
@@ -1,4 +1,4 @@
-name: Validate and Index FASTA
+name: Validate and Index All FASTA Files
 
 on:
   push:
@@ -6,9 +6,6 @@ on:
       - main
     paths:
       - 'fasta/*.fasta'
-      - 'csv/*.csv'
-      - 'gff/*.gff'
-      - '.github/workflows/validate_fasta.yml'
 
 jobs:
   validate_fasta:
@@ -21,27 +18,30 @@ jobs:
     - name: Validate FASTA
       run: |
         for fasta_file in fasta/*.fasta; do
-          echo "Validating fasta file: $fasta_file"
-          # Check corresponding CSV and GFF files
-          base_name=$(basename "$fasta_file" .fasta)
-          if [[ ! -f "csv/${base_name}.csv" && ! -f "gff/${base_name}.gff" ]]; then
-            echo "Error: Corresponding CSV or GFF file for $fasta_file not found."
-            exit 1
+          if [[ "$fasta_file" == *.fasta ]]; then
+            echo "Validating Fasta file: $fasta_file"
+            # Check corresponding CSV and GFF files
+            base_name=$(basename "$fasta_file" .fasta)
+            if [[ ! -f "csv/${base_name}.csv" && ! -f "gff/${base_name}.gff" ]]; then
+              echo "Error: Corresponding CSV or GFF file for $fasta_file not found."
+              exit 1
+            fi
+            # Validate FASTA file
+            docker run --rm -v ${{ github.workspace }}:/workspace quay.io/biocontainers/py_fasta_validator:0.6--py38hd638cd3_4 py_fasta_validator -f /workspace/$fasta_file
           fi
-          # Validate FASTA file
-          docker run --rm -v ${{ github.workspace }}:/workspace quay.io/biocontainers/py_fasta_validator:0.6--py38hd638cd3_4 py_fasta_validator -f /workspace/$fasta_file
         done
 
     - name: Index FASTA with Samtools
-      if: success()
       run: |
-        for fasta_file in fasta/.*fasta; do
-          # Index FASTA file
-          docker run --rm -v ${{ github.workspace }}:/workspace quay.io/biocontainers/samtools:1.20--h50ea8bc_0 samtools faidx /workspace/$fasta_file
+        for fasta_file in fasta/*.fasta; do
+          if [[ "$fasta_file" == *.fasta ]]; then
+            echo "Index Fasta file: $fasta_file"
+            # Index FASTA file
+            docker run --rm -v ${{ github.workspace }}:/workspace quay.io/biocontainers/samtools:1.20--h50ea8bc_0 samtools faidx /workspace/$fasta_file
+          fi
         done
 
     - name: Commit and push index files
-      if: success()
       run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
